export const types = {
  normal: {
    idType: 1,
    name: "normal",
    strongAgainst: [],
    weakAgainst: [13, 17],
    immune: [14],
  },
  fire: {
    idType: 2,
    name: "fire",
    strongAgainst: [4,6,12,17],
    weakAgainst: [2,3,13,15],
    immune: [],
  },

  water: {
    idType: 3,
    name: "water",
    strongAgainst: [2,9,13],
    weakAgainst: [3,4,15],
    immune: [],
  },

  plant: {
    idType: 4,
    name: "plant",
    strongAgainst: [3,10,13],
    weakAgainst: [2,4,8,10,12,15,17],
    immune: [],
  },
  electric: {
    idType: 5,
    name: "electric",
    strongAgainst: [3,10],
    weakAgainst: [4,5,15],
    immune: [9],
  },
  ice: {
    idType: 6,
    name: "ice",
    strongAgainst: [4,9,10,15],
    weakAgainst: [2,3,6,17],
    immune: [],
  },
  fighting: {
    idType: 7,
    name: "fighting",
    strongAgainst: [1,6,13,16,17],
    weakAgainst: [8,10,11,12,18],
    immune: [14],
  },
  poison: {
    idType: 8,
    name: "poison",
    strongAgainst: [4,18],
    weakAgainst: [8,9,13,14],
    immune: [17],
  },
  ground: {
    idType: 9,
    name: "ground",
    strongAgainst: [2,5,8,13,17],
    weakAgainst: [4,12],
    immune: [10],
  },
  flying: {
    idType: 10,
    name: "flying",
    strongAgainst: [4,7,12],
    weakAgainst: [5,13,17],
    immune: [],
  },
  psychic: {
    idType: 11,
    name: "psychic",
    strongAgainst: [7,8],
    weakAgainst: [11,17],
    immune: [16],
  },
  bug: {
    idType: 12,
    name: "bug",
    strongAgainst: [4,11,16],
    weakAgainst: [2,7,8,10,14,17,18],
    immune: [],
  },
  rock: {
    idType: 13,
    name: "rock",
    strongAgainst: [2,6,10,12],
    weakAgainst: [7,9,17],
    immune: [],
  },
  ghost: {
    idType: 14,
    name: "ghost",
    strongAgainst: [11,14],
    weakAgainst: [16],
    immune: [1],
  },
  dragon: {
    idType: 15,
    name: "dragon",
    strongAgainst: [15],
    weakAgainst: [17],
    immune: [18],
  },
  dark: {
    idType: 16,
    name: "dark",
    strongAgainst: [11,14],
    weakAgainst: [16,18],
    immune: [],
  },
  steel: {
    idType: 17,
    name: "steel",
    strongAgainst: [6,13,18],
    weakAgainst: [2,3,5,17],
    immune: [],
  },
  fairy: {
    idType: 18,
    name: "fairy",
    strongAgainst: [7,15,16],
    weakAgainst: [2,8,17],
    immune: [],
  },
};
